# Generated by Django 3.1.3 on 2020-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('title', models.TextField()),
            ],
        ),
    ]
